// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public interface AuthenticateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthenticateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>optional string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>optional string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
