// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public interface GroupMessagePushResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupMessagePushResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional int64 groupId = 3;</code>
   */
  long getGroupId();

  /**
   * <code>optional int64 senderId = 4;</code>
   */
  long getSenderId();

  /**
   * <code>optional int64 receiverId = 5;</code>
   */
  long getReceiverId();

  /**
   * <code>optional string sendContent = 6;</code>
   */
  java.lang.String getSendContent();
  /**
   * <code>optional string sendContent = 6;</code>
   */
  com.google.protobuf.ByteString
      getSendContentBytes();

  /**
   * <code>optional int64 timeStamp = 7;</code>
   */
  long getTimeStamp();
}
