// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public final class Im {
  private Im() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthenticateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthenticateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageSendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageSendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageSendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageSendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessagePushRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessagePushRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessagePushResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessagePushResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010im.proto\"D\n\023AuthenticateRequest\022\013\n\003uid" +
      "\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003" +
      "\"5\n\024AuthenticateResponse\022\014\n\004code\030\001 \001(\005\022\017" +
      "\n\007message\030\002 \001(\t\"O\n\022MessageSendRequest\022\020\n" +
      "\010senderId\030\001 \001(\t\022\022\n\nreceiverId\030\002 \001(\t\022\023\n\013s" +
      "endContent\030\003 \001(\t\"4\n\023MessageSendResponse\022" +
      "\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"u\n\022Messag" +
      "ePushRequest\022\021\n\tmessageId\030\001 \001(\003\022\020\n\010sende" +
      "rId\030\002 \001(\t\022\022\n\nreceiverId\030\003 \001(\t\022\023\n\013sendCon" +
      "tent\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\003\"G\n\023Message",
      "PushResponse\022\014\n\004code\030\001 \001(\005\022\021\n\tmessageId\030" +
      "\002 \001(\003\022\017\n\007message\030\003 \001(\tB\035\n\031com.yjlan.im.c" +
      "ommon.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AuthenticateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuthenticateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthenticateRequest_descriptor,
        new java.lang.String[] { "Uid", "Token", "Timestamp", });
    internal_static_AuthenticateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AuthenticateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthenticateResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_MessageSendRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MessageSendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageSendRequest_descriptor,
        new java.lang.String[] { "SenderId", "ReceiverId", "SendContent", });
    internal_static_MessageSendResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MessageSendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageSendResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_MessagePushRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MessagePushRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessagePushRequest_descriptor,
        new java.lang.String[] { "MessageId", "SenderId", "ReceiverId", "SendContent", "Timestamp", });
    internal_static_MessagePushResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_MessagePushResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessagePushResponse_descriptor,
        new java.lang.String[] { "Code", "MessageId", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
