// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public interface MessagePushResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessagePushResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional int64 messageId = 2;</code>
   */
  long getMessageId();

  /**
   * <code>optional string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
