// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public interface MessageSendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageSendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string senderId = 1;</code>
   */
  java.lang.String getSenderId();
  /**
   * <code>optional string senderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>optional string receiverId = 2;</code>
   */
  java.lang.String getReceiverId();
  /**
   * <code>optional string receiverId = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>optional string sendContent = 3;</code>
   */
  java.lang.String getSendContent();
  /**
   * <code>optional string sendContent = 3;</code>
   */
  com.google.protobuf.ByteString
      getSendContentBytes();
}
