// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public interface MessagePushRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessagePushRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 messageId = 1;</code>
   */
  long getMessageId();

  /**
   * <code>optional int64 senderId = 2;</code>
   */
  long getSenderId();

  /**
   * <code>optional int64 receiverId = 3;</code>
   */
  long getReceiverId();

  /**
   * <code>optional string sendContent = 4;</code>
   */
  java.lang.String getSendContent();
  /**
   * <code>optional string sendContent = 4;</code>
   */
  com.google.protobuf.ByteString
      getSendContentBytes();

  /**
   * <code>optional int64 timestamp = 5;</code>
   */
  long getTimestamp();
}
