// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public interface MessageSendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageSendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional string senderId = 3;</code>
   */
  java.lang.String getSenderId();
  /**
   * <code>optional string senderId = 3;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>optional string receiverId = 4;</code>
   */
  java.lang.String getReceiverId();
  /**
   * <code>optional string receiverId = 4;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>optional int64 timestamp = 5;</code>
   */
  long getTimestamp();
}
