// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

public interface SendDelivererRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendDelivererRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string instanceCode = 1;</code>
   */
  java.lang.String getInstanceCode();
  /**
   * <code>optional string instanceCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getInstanceCodeBytes();
}
