// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im.proto

package com.yjlan.im.common.proto;

/**
 * Protobuf type {@code SendDelivererRequest}
 */
public  final class SendDelivererRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SendDelivererRequest)
    SendDelivererRequestOrBuilder {
  // Use SendDelivererRequest.newBuilder() to construct.
  private SendDelivererRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendDelivererRequest() {
    instanceCode_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SendDelivererRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            instanceCode_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yjlan.im.common.proto.Im.internal_static_SendDelivererRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yjlan.im.common.proto.Im.internal_static_SendDelivererRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yjlan.im.common.proto.SendDelivererRequest.class, com.yjlan.im.common.proto.SendDelivererRequest.Builder.class);
  }

  public static final int INSTANCECODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object instanceCode_;
  /**
   * <code>optional string instanceCode = 1;</code>
   */
  public java.lang.String getInstanceCode() {
    java.lang.Object ref = instanceCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instanceCode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string instanceCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getInstanceCodeBytes() {
    java.lang.Object ref = instanceCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instanceCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getInstanceCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, instanceCode_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getInstanceCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, instanceCode_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yjlan.im.common.proto.SendDelivererRequest)) {
      return super.equals(obj);
    }
    com.yjlan.im.common.proto.SendDelivererRequest other = (com.yjlan.im.common.proto.SendDelivererRequest) obj;

    boolean result = true;
    result = result && getInstanceCode()
        .equals(other.getInstanceCode());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + INSTANCECODE_FIELD_NUMBER;
    hash = (53 * hash) + getInstanceCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yjlan.im.common.proto.SendDelivererRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yjlan.im.common.proto.SendDelivererRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SendDelivererRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SendDelivererRequest)
      com.yjlan.im.common.proto.SendDelivererRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yjlan.im.common.proto.Im.internal_static_SendDelivererRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yjlan.im.common.proto.Im.internal_static_SendDelivererRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yjlan.im.common.proto.SendDelivererRequest.class, com.yjlan.im.common.proto.SendDelivererRequest.Builder.class);
    }

    // Construct using com.yjlan.im.common.proto.SendDelivererRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      instanceCode_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yjlan.im.common.proto.Im.internal_static_SendDelivererRequest_descriptor;
    }

    public com.yjlan.im.common.proto.SendDelivererRequest getDefaultInstanceForType() {
      return com.yjlan.im.common.proto.SendDelivererRequest.getDefaultInstance();
    }

    public com.yjlan.im.common.proto.SendDelivererRequest build() {
      com.yjlan.im.common.proto.SendDelivererRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yjlan.im.common.proto.SendDelivererRequest buildPartial() {
      com.yjlan.im.common.proto.SendDelivererRequest result = new com.yjlan.im.common.proto.SendDelivererRequest(this);
      result.instanceCode_ = instanceCode_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yjlan.im.common.proto.SendDelivererRequest) {
        return mergeFrom((com.yjlan.im.common.proto.SendDelivererRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yjlan.im.common.proto.SendDelivererRequest other) {
      if (other == com.yjlan.im.common.proto.SendDelivererRequest.getDefaultInstance()) return this;
      if (!other.getInstanceCode().isEmpty()) {
        instanceCode_ = other.instanceCode_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yjlan.im.common.proto.SendDelivererRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yjlan.im.common.proto.SendDelivererRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object instanceCode_ = "";
    /**
     * <code>optional string instanceCode = 1;</code>
     */
    public java.lang.String getInstanceCode() {
      java.lang.Object ref = instanceCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instanceCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string instanceCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceCodeBytes() {
      java.lang.Object ref = instanceCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string instanceCode = 1;</code>
     */
    public Builder setInstanceCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      instanceCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string instanceCode = 1;</code>
     */
    public Builder clearInstanceCode() {
      
      instanceCode_ = getDefaultInstance().getInstanceCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string instanceCode = 1;</code>
     */
    public Builder setInstanceCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      instanceCode_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:SendDelivererRequest)
  }

  // @@protoc_insertion_point(class_scope:SendDelivererRequest)
  private static final com.yjlan.im.common.proto.SendDelivererRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yjlan.im.common.proto.SendDelivererRequest();
  }

  public static com.yjlan.im.common.proto.SendDelivererRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendDelivererRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendDelivererRequest>() {
    public SendDelivererRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendDelivererRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SendDelivererRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendDelivererRequest> getParserForType() {
    return PARSER;
  }

  public com.yjlan.im.common.proto.SendDelivererRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

